### ISSUE TITLE
Alexa script audit and clean up

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#108]
There a number of Alexa responses that are long winded or not following the[Alexa guidelines](https://developer.amazon.com/designing-for-voice/what-alexa-says/). 

We should review all of our responses and try to make them conform to these guidelines.

**Comment by alidaniell** [comment]
Some snow emergency parking responses are very wordy, because the comments are pulled from the comment column of http://bostonopendata-boston.opendata.arcgis.com/datasets/53ebc23fcc654111b642f70e61c63852_0.csv.  Until we cut down the comments or perhaps prompt user to hear more info (to include the comment and phone number), this output will remain wordy.

**Comment by jmartini** [comment]
Closed with PR #116
