### ISSUE TITLE
Improve documentation format and add wiki

### ISSUE THREAD

**Issue by jmartini** [codeforboston/voiceapp311#127]
Our readme is getting very big with a lot of different information. Lets make the Readme higher level and move the detailed info into a wiki: https://guides.github.com/features/wikis/

**Comment by curranjm** [comment]
I finished moving the readMe sections over to the wiki, which @Lou-Boston started (the wiki is directly editable in the web interface, so if he comes back it should be easy to pick up where I left off). Now that the installation instructions have been ported to the wiki, I'd like to get them updated to reflect the changes to deploy tools since we point new people to those instructions so often.

**Comment by Lou-Boston** [comment]
Thank you. I got really busy here at work so I won't be able to get to this
until next week.

Lou

**Comment by curranjm** [comment]
I think the only thing left to do on this one is put in a PR to update project READMEs to point to the wiki.
